name: GitHub Actions Demo
run-name: ${{ github.actor }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name:  Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install deps
        run: npm install
      - name: Test backend
        run: npm test
      - name: Build project
        run: npm run build
